# Cloudflare Pages configuration
name = "vadivelu-cars-customer"
compatibility_date = "2024-01-15"

[env.production]
name = "vadivelu-cars-customer"

[env.preview]
name = "vadivelu-cars-customer-preview"
